<a href="https://colab.research.google.com/github/9Pawel3/Data-Science-and-Machine-Learning/blob/main/Logistic%20Regression%20-%20bank%20loan%20dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

path = '/content/Churn_Modelling.csv'

df = pd.read_csv(path)

In [2]:
# Check df info

df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [5]:
# Remove irrelevant data
df.columns

df = df.drop(columns=['RowNumber', 'CustomerId', 'Surname'], index = 1)

In [7]:
# Encode categorical data
df = pd.get_dummies(df, drop_first = True)

df

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,0,0,0
2,502,42,8,159660.80,3,1,0,113931.57,1,0,0,0
3,699,39,1,0.00,2,0,0,93826.63,0,0,0,0
4,850,43,2,125510.82,1,1,1,79084.10,0,0,1,0
5,645,44,8,113755.78,2,1,0,149756.71,1,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,0,0,1
9996,516,35,10,57369.61,1,1,1,101699.77,0,0,0,1
9997,709,36,7,0.00,1,0,1,42085.58,1,0,0,0
9998,772,42,3,75075.31,2,1,0,92888.52,1,1,0,1
9999,792,28,4,130142.79,1,1,0,38190.78,0,0,0,0

In [14]:
# Check target info
df['Exited'].value_counts()

0    7962
1    2037
Name: Exited, dtype: int64

In [16]:
# Split data into attribute and target

X = df.drop('Exited', axis=1)
y = df['Exited']

In [19]:
# Split data into test and train sets bearing in my imbalance of target values
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,
                test_size=0.2, random_state=42, stratify=y)

In [23]:
# Feature scale
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

array([[ 1.09560443, -1.90619897, -0.35998364, ..., -0.58856294,
         1.75709381,  0.90875676],
       [-0.45738738,  0.10025145,  1.37007473, ...,  1.69905364,
        -0.56912158,  0.90875676],
       [ 1.09560443,  0.19579671,  0.33203971, ...,  1.69905364,
        -0.56912158,  0.90875676],
       ...,
       [-0.55056688,  0.29134197, -0.35998364, ..., -0.58856294,
        -0.56912158, -1.10040447],
       [ 1.20949049,  0.86461352,  1.37007473, ..., -0.58856294,
        -0.56912158,  0.90875676],
       [-0.02254967,  0.673523  ,  1.37007473, ..., -0.58856294,
         1.75709381,  0.90875676]])

In [24]:
# Use classification algorithm - logistic regression

from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()

lr.fit(X_train, y_train)

LogisticRegression()

In [25]:
# Perform prediction and check accuracy

y_pred1 = lr.predict(X_test)

from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred1)

0.8115